#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinScanditSDKDemoAndroid.Resource", IsApplication=true)]

namespace XamarinScanditSDKDemoAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int camera_swap_icon = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int camera_swap_icon_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flashlight_turn_off_icon = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flashlight_turn_off_icon_pressed = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flashlight_turn_on_icon = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flashlight_turn_on_icon_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ic_btn_search = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ocr_turn_off_icon = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ocr_turn_on_icon = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int scan_line_blue = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int scan_line_white = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int scandit_logo = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int scandit_logo2x = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int scandit_logo3x = 2130968590;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int version = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
