// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using Xamarin.Themes;
using TrackBeamTheme_Sample_iOS.Model;
using Xamarin.Themes.TrackBeam;
using Xamarin.Themes.Core;

#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif

namespace TrackBeamTheme_Sample_iOS.Views.iPhone {
	public partial class ThemeListCell : UITableViewCell {
		public ThemeListCell (IntPtr handle) : base (handle)
		{
		}

		internal void Init (Track track)
		{
			trackLabel.Text = track.Name;
			artistLabel.Text = track.Artist;
			albumImageView.Image = track.Image;
			lengthLabel.Text = track.Length;


			trackLabel.TextColor = ThemeManager.GetCurrent<TrackBeamTheme>().BaseTintColor;
			this.BackgroundColor = UIColor.Clear;
		}

		protected override void Dispose (bool disposing)
		{
			ReleaseDesignerOutlets ();
			base.Dispose (disposing);
		}
	}
}
